import type { Metadata } from "next";
// import { DM_Sans } from "next/font/google";
import { Poppins } from "next/font/google";
import clsx from "clsx";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ['400'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(poppins.className, 'antialiased')}>{children}</body>
    </html>
  );
}
